"use client";

import React, { useEffect, useState } from 'react';
import { runSemanticETLAction } from '@/app/actions/semantic-etl';
import { SciFiRenderer } from '@/components/ui/SciFiRenderer';
import { SciFiQnA } from '@/components/ui/SciFiQnA';
import { SciFiSlicers } from '@/components/ui/SciFiSlicers';
import { UISpec } from '@/lib/semantic-etl/schemas';
import { Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';

export default function AnalyticsDashboard() {
  const [uiSpec, setUiSpec] = useState<UISpec | null>(null);
  const [loading, setLoading] = useState(true);
  const [metrics, setMetrics] = useState<any>(null);

  useEffect(() => {
    async function loadDashboard() {
      setLoading(true);
      try {
        const result = await runSemanticETLAction({
          datasetName: "Live Business Analytics",
          datasetDescription: "Realtime data voor dropshipping omzet, ROAS, en server load.",
          taskGoal: "Maak een futuristisch dashboard met grafieken over de omzet, winstmarge en 1 grote server load KPI.",
          userRoles: ["CEO", "Admin"],
          branding: {
            companyName: "Rebuild Your Life",
            primaryColor: "#00ffea",
            accentColor: "#ff00aa"
          }
        });
        
        if (result.spec) {
          setUiSpec(result.spec);
        }
        if (result.metrics) {
          setMetrics(result.metrics);
        }
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    }

    loadDashboard();
  }, []);

  const handleNewSpec = (newSpec: UISpec) => {
    // When Q&A generates a new spec, we merge or replace the current one.
    // For now, we prepend the new page generated by Q&A.
    setUiSpec(prev => {
      if (!prev) return newSpec;
      return {
        ...prev,
        pages: [...newSpec.pages, ...prev.pages]
      };
    });
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[80vh] text-cyan-400 font-mono">
        <Loader2 className="w-12 h-12 animate-spin mb-4 text-cyan-400 shadow-[0_0_15px_#00ffea]" />
        <p className="animate-pulse tracking-widest uppercase text-sm">Semantic ETL Initializing...</p>
        <p className="text-xs text-cyan-900 mt-2">Connecting to Neural Core...</p>
      </div>
    );
  }

  if (!uiSpec) {
    return <div className="p-8 text-red-500">Failed to load UI Spec</div>;
  }

  return (
    <div className="w-full max-w-[1600px] mx-auto p-4 md:p-8">
      {/* Office 365 Toolbar (Sci-Fi Edition) */}
      <motion.div 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-8 space-y-6"
      >
        <div className="flex flex-col md:flex-row gap-6 items-start md:items-center justify-between">
          <div>
            <h1 className="text-2xl md:text-3xl font-black uppercase tracking-widest text-white mb-2">
              Command Center
            </h1>
            <p className="text-zinc-500 font-mono text-xs">Office 365 Neural Link Active</p>
          </div>
          <div className="w-full md:w-1/2">
            <SciFiQnA onSpecGenerated={handleNewSpec} />
          </div>
        </div>

        <SciFiSlicers />
      </motion.div>

      {/* Main Dashboard Render */}
      <SciFiRenderer spec={uiSpec} />

      {/* Background Metrics */}
      {metrics && (
        <div className="fixed bottom-4 right-4 bg-black/80 border border-cyan-900/50 p-2 rounded text-[10px] text-cyan-500 font-mono z-50 pointer-events-none backdrop-blur-sm">
          <p>ETL MS: {metrics.processingTimeMs}ms</p>
          <p>Attempts: {metrics.attempts}</p>
        </div>
      )}
    </div>
  );
}
