import os
import json
import logging
from openai import AsyncOpenAI

logger = logging.getLogger("aeip.llm_router")

# Initialize OpenAI client (requires OPENAI_API_KEY environment variable)
try:
    client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY", "dummy"))
except Exception as e:
    logger.warning("Could not initialize OpenAI client: %s", e)
    client = None

async def invoke(agent_key: str, context: dict) -> dict:
    """
    Routes a task payload to the appropriate LLM prompt based on the agent_key.
    Returns a dictionary with the agent's decision.
    """
    logger.info("LLM Router invoked for agent %s", agent_key)
    
    # If no API key is provided, return a robust fallback so the live system does not crash
    if not os.getenv("OPENAI_API_KEY"):
        logger.warning("No OPENAI_API_KEY found, using deterministic fallback for %s", agent_key)
        if "copywriter" in agent_key:
            return {"draft_copy": f"Premium ad variant generated by {agent_key} based on context."}
        return {"action": f"Automated decision by {agent_key}"}

    # Define system prompts per agent
    system_prompts = {
        "lead_gen_v1": "You are the Lead Generation Agent. Analyze the context and decide the next nurture sequence.",
        "copywriter_v1": "You are the Copywriter Agent. Draft premium, high-converting ad copy based on the context.",
        "support_v1": "You are the Customer Support Agent. Formulate a polite and helpful response."
    }
    
    system_prompt = system_prompts.get(agent_key, "You are a helpful AI assistant. Respond in JSON format.")
    
    try:
        response = await client.chat.completions.create(
            model="gpt-4o", # Default to gpt-4o for complex tasks
            response_format={ "type": "json_object" },
            messages=[
                {"role": "system", "content": f"{system_prompt}\nAlways respond with valid JSON."},
                {"role": "user", "content": f"Context: {json.dumps(context)}\nProvide your output in JSON format."}
            ],
            temperature=0.7,
            max_tokens=500
        )
        
        content = response.choices[0].message.content
        return json.loads(content)
        
    except Exception as e:
        logger.error("LLM API call failed: %s", e)
        # Fallback payload so the task can gracefully fail or retry downstream
        return {"error": "LLM generation failed", "details": str(e)}
